version: "3.3"

services:
  qnd10app:
    image: smartquail/qnd10app:latest
    restart: unless-stopped
    environment:
      - PORT=9000
    env_file:
      - .env
    depends_on:
      - smartquaildb
    expose:
      - 9000
    volumes:
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/static
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/media
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/staticfiles
    networks: 
      - lansmartquail

  smartquaildb:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: always
    command: -p 5432
    expose:
      - 5432
    volumes:
      - smartquaildb_data-qnode10:/var/lib/postgresql/data/
    networks: 
      - lansmartquail

  nginx:
    image: smartquail/qnd10_nginx:dev
    restart: unless-stopped
    depends_on:
      - qnd10app
    ports:
      - 80:80
      - 443:443  
    volumes:
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/static
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/media
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/staticfiles
    networks: 
      - lansmartquail

 

volumes:
  static-data-qnd10:
  smartquaildb_data-qnode10:

networks: 
   lansmartquail:
       driver: bridge
