# Generated by Django 4.2.16 on 2024-12-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0003_sbmproduct_image1_sbmproduct_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbmproduct',
            name='color',
            field=models.CharField(blank=True, choices=[('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)'), ('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)'), ('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)'), ('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)'), ('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)'), ('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)')], db_index=True, max_length=200, null=True),
        ),
    ]
