# Generated by Django 4.2.16 on 2024-12-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0004_sbmproduct_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbmproduct',
            name='color',
            field=models.CharField(blank=True, choices=[('rgb(133, 54, 140)', 'SBM-CRM+AI+I+D'), ('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)'), ('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)'), ('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)'), ('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)'), ('SBM-CRM+AI+I+D', 'rgb(133, 54, 140)')], db_index=True, max_length=200, null=True),
        ),
    ]
