# Generated by Django 4.2.16 on 2024-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0009_alter_sbmproduct_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbmproduct',
            name='background',
            field=models.ImageField(blank=True, upload_to='products/smartbusinessmedia/background/%Y/%m/%d'),
        ),
    ]
