# Generated by Django 4.2.16 on 2024-12-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0012_sbmproduct_datasheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbmproduct',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
    ]
