# Generated by Django 4.2.16 on 2024-12-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0013_sbmproduct_terms_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbmproduct',
            name='color',
            field=models.CharField(blank=True, choices=[('rgb(133, 54, 140)', 'SBM-CRM+AI+I+D'), ('#262625', 'SBM-CRM'), ('#662d14', 'SBM-CRM+A'), ('#247832', 'SBM-CRM+I+D'), ('#7c7a21', 'SBM-CRM+A+I+D'), ('#283f75', 'SBM-CRM+AI'), ('#388e86', 'SBM-CRM+A+AI'), ('#251f25', 'SBM-CRM+A+AI+I+D')], db_index=True, max_length=200, null=True),
        ),
    ]
