# Generated by Django 4.2.16 on 2024-12-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0014_alter_sbmproduct_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBMProductManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/background/%Y/%m/%d')),
                ('bg_image', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/background/%Y/%m/%d')),
                ('color', models.CharField(blank=True, choices=[('rgb(133, 54, 140)', 'SBM-CRM+AI+I+D'), ('#262625', 'SBM-CRM'), ('#662d14', 'SBM-CRM+A'), ('#247832', 'SBM-CRM+I+D'), ('#7c7a21', 'SBM-CRM+A+I+D'), ('#283f75', 'SBM-CRM+AI'), ('#388e86', 'SBM-CRM+A+AI'), ('#251f25', 'SBM-CRM+A+AI+I+D')], db_index=True, max_length=200, null=True)),
                ('title_intro', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('subtitle_title_intro', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sbmshop.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sbmshop.sbmproduct')),
            ],
        ),
    ]
