# Generated by Django 4.2.16 on 2024-12-13 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0015_sbmproductmanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_intro', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('subtitle_title_intro', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True)),
                ('manuales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sbmshop.sbmproductmanual')),
            ],
        ),
    ]
