# Generated by Django 4.2.16 on 2024-12-16 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0017_alter_sbmproductmanual_color_sbmstaffitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBMTechnologiesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(blank=True, upload_to='products/smartbusinessmedia/ProductBrands/%Y/%m/%d')),
                ('sbmproductstechno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies_products', to='sbmshop.sbmproduct')),
            ],
        ),
    ]
