# Generated by Django 4.2.16 on 2024-12-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0020_alter_sbmproduct_item1_alter_sbmproduct_item2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sbmmodels_p1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sbmmodels_p2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sbmmodels_p3',
            field=models.TextField(blank=True),
        ),
    ]
