# Generated by Django 4.2.16 on 2024-12-17 16:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0021_category_sbmmodels_p1_category_sbmmodels_p2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sbmmodels_p1',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='sbmmodels_p2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='sbmmodels_p3',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
