# Generated by Django 4.2.16 on 2024-12-19 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbmcoupons', '0002_coupon_promo_name_alter_coupon_code'),
        ('sbmshop', '0022_alter_category_sbmmodels_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbmproduct',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='sbmcoupons.coupon'),
        ),
    ]
