# Generated by Django 4.2.16 on 2024-12-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0025_alter_sbmstaffitem_sbmproducts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbmtechnologiesitem',
            name='logo_img',
        ),
        migrations.AddField(
            model_name='sbmtechnologiesitem',
            name='App_type',
            field=models.CharField(blank=True, choices=[('Simple IT Cloud Web App+CRM', 'Simple IT Cloud Web App+CRM'), ('Simple IT Cloud Web App+CRM+I+D', 'Simple IT Cloud Web App+CRM+I+D'), ('Simple IT Cloud Web App+CRM+I+D+A', 'Simple IT Cloud Web App+CRM+I+D+A'), ('Simple IT Cloud Web App+CRM+A', 'Simple IT Cloud Web App+CRM+A'), ('Simple IT Cloud Web App+CRM+AI', 'Simple IT Cloud Web App+CRM+AI'), ('Simple IT Cloud Web App+CRM+AI+A', 'Simple IT Cloud Web App+CRM+AI+A'), ('Simple IT Cloud Web App+CRM+AI+I+D', 'Simple IT Cloud Web App+CRM+AI+I+D'), ('Simple IT Cloud Web App+CRM+AI+A+I+D', 'Simple IT Cloud Web App+CRM+AI+A+I+D')], db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sbmtechnologiesitem',
            name='Domain',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sbmtechnologiesitem',
            name='Node_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sbmtechnologiesitem',
            name='Types_reliable_systems',
            field=models.CharField(blank=True, choices=[('Low reliable', 'Low reliable'), ('Reliable', 'Reliable'), ('High reliable', 'High reliable')], db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sbmtechnologiesitem',
            name='version',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
