# Generated by Django 4.2.16 on 2024-12-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0026_remove_sbmtechnologiesitem_logo_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbmtechnologiesitem',
            name='memory_resourse',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sbmtechnologiesitem',
            name='procesing_resourse',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sbmtechnologiesitem',
            name='storge_resourse',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sbmstaffitem',
            name='ceo_sector',
            field=models.CharField(choices=[('SmartBusinessMedia Community Manager', 'SmartBusinessMedia Community Manager'), ('Chief Officer of Technologies', 'Chief Officer of Technologies'), ('SmartBusinessMedia Project Manager', 'SmartBusinessMedia Project Manager'), ('Chief Officer SmartBusinessMedia', 'Chief Officer SmartBusinessMedia ')], db_index=True, max_length=200),
        ),
    ]
