# Generated by Django 4.2.16 on 2024-12-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmshop', '0027_sbmtechnologiesitem_memory_resourse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbmproduct',
            old_name='cloud_technologies',
            new_name='terms_policies',
        ),
        migrations.AlterField(
            model_name='sbmtechnologiesitem',
            name='Types_reliable_systems',
            field=models.CharField(blank=True, choices=[('Low ', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, max_length=500, null=True),
        ),
    ]
