version: "3.3"

services:
  qnd41app:
    image: smartquail/qnd41app:latest
    restart: unless-stopped
    environment:
      - PORT=9000
    env_file:
      - .env_stage
    depends_on:
      - smartquaildb
      - postfix
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/static
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/staticfiles
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/media
    networks:
      - lansmartquail

  smartquaildb:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - smartquaildb_data-qnd41:/var/lib/postgresql/data/
    networks:
      - lansmartquail

  nginx:
    image: smartquail/qnd41_nginx:prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=80
    depends_on:
      - qnd41app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/static
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/staticfiles
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/media
      - certbot-web_2:/vol/www
      - proxy-dhparams_2:/vol/proxy
      - letsencrypt_certs:/etc/letsencrypt
    networks:
      - lansmartquail




  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"  # Puerto de Redis
      - "8001:8001"
    volumes:
      - redis_data:/root/redis
      - redis_data_config:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=ms95355672
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - lansmartquail




volumes:
  certbot-web_2:
  proxy-dhparams_2:
  letsencrypt_certs:
  static-data-qnd41:
  smartquaildb_data-qnd41:
  redis_data:
  redis_data_config:

networks:
  lansmartquail:
    driver: bridge
