version: "3.3"

services:
  qnd41app:
    image: smartquail/qnd41app:latest
    restart: unless-stopped
    env_file:
      - .env_stage
    environment:
      - PORT=9000
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - smartquaildb
      - redis
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/static
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/staticfiles
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/media
    networks:
      - lansmartquail

  smartquaildb:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - smartquaildb_data-qnd41:/var/lib/postgresql/data/
    networks:
      - lansmartquail

  nginx:
    image: smartquail/qnd41_nginx:prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=80
    depends_on:
      - qnd41app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/static
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/staticfiles
      - static-data-qnd41:/qnd41app/qnd41app/qnd41app/media
      - certbot-web_2:/vol/www
      - proxy-dhparams_2:/vol/proxy
      - letsencrypt_certs:/etc/letsencrypt
    networks:
      - lansmartquail




  redis:
    image: redis/redis-stack:latest
    container_name: redis
    env_file:
      - .env_redis
    ports:
      - "6379:6379"  # Puerto de Redis
      - "8001:8001"
    volumes:
      - redis_data:/root/redis
      - redis_data_config:/usr/local/etc/redis/redis.conf
    networks:
      - lansmartquail

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env_stage
    ports:
      - "5672:5672"  # Puerto de RabbitMQ
      - "15672:15672"  # Puerto del panel de gestión web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - lansmartquail




volumes:
  certbot-web_2:
  proxy-dhparams_2:
  letsencrypt_certs:
  static-data-qnd41:
  smartquaildb_data-qnd41:
  redis_data:
  redis_data_config:
  rabbitmq_data:

networks:
  lansmartquail:
    driver: bridge
