# Generated by Django 4.2.13 on 2024-06-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name': 'Currículum de autor'},
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Escriba el nombre del proyecto al que desea vincular el archivo'),
        ),
    ]
