# Generated by Django 4.2.13 on 2024-06-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_tematica_project_tematica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, verbose_name='Describa la actividad que desempeña el autor en el proyecto'),
        ),
        migrations.AlterField(
            model_name='bibliographicreference',
            name='journal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Escriba el nombre de la editorial'),
        ),
        migrations.AlterField(
            model_name='bibliographicreference',
            name='publication_year',
            field=models.PositiveIntegerField(verbose_name='Escriba el año de publicación'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='end_date',
            field=models.DateField(help_text='Escribir la fecha de final de la actividad. Ej. 01/15/2024', verbose_name='Fecha de finalización de actividad'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='start_date',
            field=models.DateField(help_text='Escribir la fecha de inicio de la actividad. Ej. 12/12/2023', verbose_name='Fecha de comienzo de actividad'),
        ),
    ]
