# Generated by Django 4.2.13 on 2024-06-03 01:07

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='confirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_de_despedida', ckeditor.fields.RichTextField(default=False, verbose_name='Términos y Condiciones de Uso')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('informacion_basica', ckeditor.fields.RichTextField()),
                ('bloque_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_5', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link_soporte_tecnico', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, choices=[('POSTULANTE', 'Postular proyectos a convocatorias'), ('PROPONIENTE', 'Proponer actividades culturales en espacios públicos')], max_length=120, null=True, verbose_name='¿Que actividad cultural desea realizar en nuestra plataforma?')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Agregar Foto de Perfil')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad')),
                ('autoidentificacion', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], help_text='¿Usted pertenece a un pueblo o nacionalidad indígena, montubio o afro-ecuatoriano?', max_length=3, null=True, verbose_name='¿Usted pertenece a un pueblo o nacionalidad indígena, montubio o afro-ecuatoriano?')),
                ('genero', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], max_length=10, null=True, verbose_name='Identidad de Género')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario')),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante_legal_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Representante Legal')),
                ('representante_legal_apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido del Representante Legal')),
                ('representante_legal_cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del Representante Legal')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RUC')),
                ('telefono_contacto', phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='telefono de contacto del representante legal')),
                ('direccion_domicilio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Domicilio')),
                ('georeferencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Georreferencia')),
                ('pagina_web', models.URLField(blank=True, null=True, verbose_name='Página Web')),
                ('tipo_personeria', models.CharField(choices=[('Natural', 'Natural'), ('Jurídico', 'Jurídico')], max_length=10, verbose_name='Tipo de Personería')),
                ('categoria_personeria', models.CharField(blank=True, choices=[('ASOCIACIONES SIN ÁNIMO DE LUCRO', 'Asociaciones sin ánimo de lucro'), ('ASOCIACIÓN DE CUENTAS DE PARTICIPACIÓN', 'Asociación de cuentas de participación'), ('SOCIEDAD DE ACCIONES SIMPLIFICADAS. S.A.S', 'Sociedad de acciones simplificadas. S.A.S'), ('COMPAÑÍA LIMITADA CÍA. LTDA.', 'Compañía limitada Cía. Ltda.'), ('EMPRESARIO INDIVIDUAL', 'Empresario individual'), ('SOCIEDAD ANÓNIMA S.A.', 'Sociedad anónima S.A.'), ('SOCIEDAD COLECTIVA', 'Sociedad colectiva'), ('SOCIEDAD COMANDATARIA', 'Sociedad comandataria'), ('SOCIEDAD COOPERATIVA', 'Sociedad cooperativa'), ('SOCIEDAD LIMITADA S.L.', 'Sociedad limitada S.L.'), ('OTRO', 'Otro')], max_length=100, null=True, verbose_name='Categoría de Personería Jurídica')),
                ('fines_lucro', models.BooleanField(blank=True, default=False, null=True, verbose_name='¿La personería jurídica tiene fines de lucro?')),
                ('actividad_principal', models.TextField(blank=True, null=True, verbose_name='Actividad Principal a la que se dedica la empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='edit_contact2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('georeferenciacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Georreferenciación')),
                ('perfil_redes_sociales', models.URLField(blank=True, null=True, verbose_name='Perfil de Redes Sociales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario para contacto')),
            ],
            options={
                'verbose_name_plural': 'Contacto de Usuarios',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='edit_contact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_residencia', django_countries.fields.CountryField(default='Ecuador', max_length=2, verbose_name='País de Residencia')),
                ('provincia_cantones_ecuador', models.CharField(blank=True, choices=[('Azuay', (('Cuenca', 'Cuenca'), ('Gualaceo', 'Gualaceo'), ('Sígsig', 'Sígsig'), ('Chordeleg', 'Chordeleg'), ('Sigsig', 'Sigsig'), ('Oña', 'Oña'), ('Girón', 'Girón'), ('Paute', 'Paute'), ('Santa Isabel', 'Santa Isabel'), ('Nabón', 'Nabón'), ('El Pan', 'El Pan'), ('Sevilla de Oro', 'Sevilla de Oro'), ('Guachapala', 'Guachapala'), ('Camilo Ponce Enríquez', 'Camilo Ponce Enríquez'), ('Suscal', 'Suscal'), ('Pucará', 'Pucará'), ('San Fernando', 'San Fernando'))), ('Bolívar', (('Guaranda', 'Guaranda'), ('Caluma', 'Caluma'), ('Chillanes', 'Chillanes'), ('Chimbo', 'Chimbo'), ('Echeandía', 'Echeandía'), ('Las Naves', 'Las Naves'))), ('Cañar', (('Azogues', 'Azogues'), ('Biblián', 'Biblián'), ('Cañar', 'Cañar'), ('La Troncal', 'La Troncal'), ('Déleg', 'Déleg'), ('El Tambo', 'El Tambo'), ('Suscal', 'Suscal'))), ('Carchi', (('Tulcán', 'Tulcán'), ('Bolívar', 'Bolívar'), ('Espejo', 'Espejo'), ('Mira', 'Mira'), ('Montúfar', 'Montúfar'), ('San Pedro de Huaca', 'San Pedro de Huaca'))), ('Chimborazo', (('Riobamba', 'Riobamba'), ('Alausí', 'Alausí'), ('Colta', 'Colta'), ('Chambo', 'Chambo'), ('Chunchi', 'Chunchi'), ('Guamote', 'Guamote'), ('Guano', 'Guano'), ('Pallatanga', 'Pallatanga'), ('Penipe', 'Penipe'))), ('Cotopaxi', (('Latacunga', 'Latacunga'), ('La Maná', 'La Maná'), ('Pangua', 'Pangua'), ('Pujilí', 'Pujilí'), ('Salcedo', 'Salcedo'), ('Saquisilí', 'Saquisilí'), ('Sigchos', 'Sigchos'))), ('El Oro', (('Machala', 'Machala'), ('Arenillas', 'Arenillas'), ('Atahualpa', 'Atahualpa'), ('Balsas', 'Balsas'), ('Chilla', 'Chilla'), ('El Guabo', 'El Guabo'), ('Huaquillas', 'Huaquillas'), ('Marcabelí', 'Marcabelí'), ('Pasaje', 'Pasaje'), ('Piñas', 'Piñas'), ('Portovelo', 'Portovelo'), ('Santa Rosa', 'Santa Rosa'), ('Zaruma', 'Zaruma'), ('Las Lajas', 'Las Lajas'))), ('Esmeraldas', (('Esmeraldas', 'Esmeraldas'), ('Eloy Alfaro', 'Eloy Alfaro'), ('Muisne', 'Muisne'), ('Quinindé', 'Quinindé'), ('San Lorenzo', 'San Lorenzo'), ('Atacames', 'Atacames'), ('Rioverde', 'Rioverde'))), ('Galápagos', (('San Cristóbal', 'San Cristóbal'), ('Isabela', 'Isabela'), ('Santa Cruz', 'Santa Cruz'))), ('Guayas', (('Guayaquil', 'Guayaquil'), ('Alfredo Baquerizo Moreno', 'Alfredo Baquerizo Moreno (Juján)'), ('Balao', 'Balao'), ('Balzar', 'Balzar'), ('Colimes', 'Colimes'), ('Coronel Marcelino Maridueña', 'Coronel Marcelino Maridueña'), ('Daule', 'Daule'), ('Durán', 'Durán'), ('El Empalme', 'El Empalme'), ('El Triunfo', 'El Triunfo'), ('Milagro', 'Milagro'), ('Naranjal', 'Naranjal'), ('Naranjito', 'Naranjito'), ('Palestina', 'Palestina'), ('Pedro Carbo', 'Pedro Carbo'), ('Samborondón', 'Samborondón'), ('Santa Lucía', 'Santa Lucía'), ('Simón Bolívar', 'Simón Bolívar'), ('Yaguachi', 'Yaguachi'), ('General Antonio Elizalde (Bucay)', 'General Antonio Elizalde (Bucay)'), ('Isidro Ayora', 'Isidro Ayora'), ('Lomas de Sargentillo', 'Lomas de Sargentillo'), ('Nobol', 'Nobol'), ('Santa Elena', 'Santa Elena'), ('La Libertad', 'La Libertad'), ('Salinas', 'Salinas'))), ('Imbabura', (('Ibarra', 'Ibarra'), ('Antonio Ante', 'Antonio Ante (Andrade Marin)'), ('Cotacachi', 'Cotacachi'), ('Otavalo', 'Otavalo'), ('Pimampiro', 'Pimampiro'), ('San Miguel de Urcuquí', 'San Miguel de Urcuquí'))), ('Loja', (('Loja', 'Loja'), ('Calvas', 'Calvas'), ('Catamayo', 'Catamayo'), ('Celica', 'Celica'), ('Chaguarpamba', 'Chaguarpamba'), ('Espíndola', 'Espíndola'), ('Gonzanamá', 'Gonzanamá'), ('Macará', 'Macará'), ('Paltas', 'Paltas'), ('Puyango', 'Puyango'), ('Saraguro', 'Saraguro'), ('Sozoranga', 'Sozoranga'), ('Zapotillo', 'Zapotillo'), ('Pindal', 'Pindal'), ('Quilanga', 'Quilanga'), ('Olmedo', 'Olmedo'))), ('Los Ríos', (('Babahoyo', 'Babahoyo'), ('Baba', 'Baba'), ('Montalvo', 'Montalvo'), ('Buena Fe', 'Buena Fe'), ('Mocache', 'Mocache'), ('Urdaneta', 'Urdaneta'), ('Ventanas', 'Ventanas'), ('Quevedo', 'Quevedo'), ('Quinsaloma', 'Quinsaloma'), ('Valencia', 'Valencia'), ('Vinces', 'Vinces'), ('Palenque', 'Palenque'))), ('Manabí', (('Portoviejo', 'Portoviejo'), ('Bolívar', 'Bolívar'), ('Chone', 'Chone'), ('El Carmen', 'El Carmen'), ('Flavio Alfaro', 'Flavio Alfaro'), ('Jipijapa', 'Jipijapa'), ('Junín', 'Junín'), ('Manta', 'Manta'), ('Montecristi', 'Montecristi'), ('Paján', 'Paján'), ('Pichincha', 'Pichincha'), ('Rocafuerte', 'Rocafuerte'), ('Santa Ana', 'Santa Ana'), ('Sucre', 'Sucre'), ('Tosagua', 'Tosagua'), ('24 de Mayo', '24 de Mayo'), ('Pedernales', 'Pedernales'), ('Olmedo', 'Olmedo'), ('Puerto López', 'Puerto López'), ('Jama', 'Jama'), ('San Vicente', 'San Vicente'))), ('Morona Santiago', (('Macas', 'Macas'), ('Gualaquiza', 'Gualaquiza'), ('Huamboya', 'Huamboya'), ('Limón Indanza', 'Limón Indanza'), ('Logroño', 'Logroño'), ('Morona', 'Morona'), ('Pablo Sexto', 'Pablo Sexto'), ('Palora', 'Palora'), ('San Juan Bosco', 'San Juan Bosco'), ('Santiago de Méndez', 'Santiago de Méndez'), ('Sucúa', 'Sucúa'), ('Taisha', 'Taisha'), ('Tiwintza', 'Tiwintza'))), ('Napo', (('Tena', 'Tena'), ('Archidona', 'Archidona'), ('El Chaco', 'El Chaco'), ('Quijos', 'Quijos'), ('Carlos Julio Arosemena Tola', 'Carlos Julio Arosemena Tola'))), ('Orellana', (('Orellana', 'Orellana'), ('Aguarico', 'Aguarico'), ('La Joya de los Sachas', 'La Joya de los Sachas'), ('Loreto', 'Loreto'))), ('Pastaza', (('Puyo', 'Puyo'), ('Arajuno', 'Arajuno'), ('Mera', 'Mera'), ('Santa Clara', 'Santa Clara'))), ('Pichincha', (('Quito', 'Quito'), ('Cayambe', 'Cayambe'), ('Mejía', 'Mejía'), ('Pedro Moncayo', 'Pedro Moncayo'), ('Rumiñahui', 'Rumiñahui'), ('San Miguel de los Bancos', 'San Miguel de los Bancos'), ('Pedro Vicente Maldonado', 'Pedro Vicente Maldonado'), ('Puerto Quito', 'Puerto Quito'))), ('Santa Elena', (('Santa Elena', 'Santa Elena'), ('La Libertad', 'La Libertad'), ('Salinas', 'Salinas'))), ('Santo Domingo de los Tsáchilas', (('Santo Domingo', 'Santo Domingo'), ('La Concordia', 'La Concordia'))), ('Sucumbíos', (('Nueva Loja', 'Nueva Loja'), ('Cascales', 'Cascales'), ('Cuyabeno', 'Cuyabeno'), ('Gonzalo Pizarro', 'Gonzalo Pizarro'), ('Putumayo', 'Putumayo'), ('Shushufindi', 'Shushufindi'), ('Sucumbíos', 'Sucumbíos'), ('Lago Agrio', 'Lago Agrio'))), ('Tungurahua', (('Ambato', 'Ambato'), ('Baños de Agua Santa', 'Baños de Agua Santa'), ('Cevallos', 'Cevallos'), ('Mocha', 'Mocha'), ('Patate', 'Patate'), ('Quero', 'Quero'), ('San Pedro de Pelileo', 'San Pedro de Pelileo'), ('Pelileo', 'Pelileo'), ('Pillaro', 'Pillaro'), ('Tisaleo', 'Tisaleo'))), ('Zamora Chinchipe', (('Zamora', 'Zamora'), ('Chinchipe', 'Chinchipe'), ('Centinela del Cóndor', 'Centinela del Cóndor'), ('Nangaritza', 'Nangaritza'), ('Palanda', 'Palanda'), ('Paquisha', 'Paquisha'), ('Yacuambi', 'Yacuambi'), ('Yantzaza', 'Yantzaza'), ('El Pangui', 'El Pangui')))], help_text='Si su pais de residencia es Ecuador, Elija una provincia. Caso contrario dejelo en blanco', max_length=255, null=True, verbose_name='Provincia y Cantones')),
                ('parroquia_quito', models.CharField(blank=True, choices=[('Conocoto', 'Conocoto'), ('Cumbayá', 'Cumbayá'), ('Chillogallo', 'Chillogallo'), ('Chilibulo', 'Chilibulo'), ('Chillos', 'Ch  illos'), ('Guamaní', 'Guamaní'), ('Calderón', 'Calderón'), ('Carapungo', 'Carapungo'), ('Pomasqui', 'Pomasqui'), ('Nayón', 'Nayón'), ('Tumbaco', 'Tumbaco'), ('Tababela', 'Tababela'), ('Quito', 'Quito')], help_text='Si su provincia de residencia es Pichincha, Elija una parroquia. Caso contrario dejelo en blanco', max_length=255, null=True, verbose_name='Parroquia de Quito')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario para contacto')),
            ],
            options={
                'verbose_name_plural': 'Contacto de Usuarios',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='DeclaracionVeracidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acepta_terminos_condiciones', models.BooleanField(default=False, verbose_name='Acepta los Términos y Condiciones de Uso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_residencias', django_countries.fields.CountryField(blank=True, help_text='Elija el país en el que usted reside', max_length=150, multiple=True, verbose_name='País de Residencia')),
                ('provincia_cantones_ecuador', models.CharField(blank=True, choices=[('Azuay', (('Cuenca', 'Cuenca'), ('Gualaceo', 'Gualaceo'), ('Sígsig', 'Sígsig'), ('Chordeleg', 'Chordeleg'), ('Sigsig', 'Sigsig'), ('Oña', 'Oña'), ('Girón', 'Girón'), ('Paute', 'Paute'), ('Santa Isabel', 'Santa Isabel'), ('Nabón', 'Nabón'), ('El Pan', 'El Pan'), ('Sevilla de Oro', 'Sevilla de Oro'), ('Guachapala', 'Guachapala'), ('Camilo Ponce Enríquez', 'Camilo Ponce Enríquez'), ('Suscal', 'Suscal'), ('Pucará', 'Pucará'), ('San Fernando', 'San Fernando'))), ('Bolívar', (('Guaranda', 'Guaranda'), ('Caluma', 'Caluma'), ('Chillanes', 'Chillanes'), ('Chimbo', 'Chimbo'), ('Echeandía', 'Echeandía'), ('Las Naves', 'Las Naves'))), ('Cañar', (('Azogues', 'Azogues'), ('Biblián', 'Biblián'), ('Cañar', 'Cañar'), ('La Troncal', 'La Troncal'), ('Déleg', 'Déleg'), ('El Tambo', 'El Tambo'), ('Suscal', 'Suscal'))), ('Carchi', (('Tulcán', 'Tulcán'), ('Bolívar', 'Bolívar'), ('Espejo', 'Espejo'), ('Mira', 'Mira'), ('Montúfar', 'Montúfar'), ('San Pedro de Huaca', 'San Pedro de Huaca'))), ('Chimborazo', (('Riobamba', 'Riobamba'), ('Alausí', 'Alausí'), ('Colta', 'Colta'), ('Chambo', 'Chambo'), ('Chunchi', 'Chunchi'), ('Guamote', 'Guamote'), ('Guano', 'Guano'), ('Pallatanga', 'Pallatanga'), ('Penipe', 'Penipe'))), ('Cotopaxi', (('Latacunga', 'Latacunga'), ('La Maná', 'La Maná'), ('Pangua', 'Pangua'), ('Pujilí', 'Pujilí'), ('Salcedo', 'Salcedo'), ('Saquisilí', 'Saquisilí'), ('Sigchos', 'Sigchos'))), ('El Oro', (('Machala', 'Machala'), ('Arenillas', 'Arenillas'), ('Atahualpa', 'Atahualpa'), ('Balsas', 'Balsas'), ('Chilla', 'Chilla'), ('El Guabo', 'El Guabo'), ('Huaquillas', 'Huaquillas'), ('Marcabelí', 'Marcabelí'), ('Pasaje', 'Pasaje'), ('Piñas', 'Piñas'), ('Portovelo', 'Portovelo'), ('Santa Rosa', 'Santa Rosa'), ('Zaruma', 'Zaruma'), ('Las Lajas', 'Las Lajas'))), ('Esmeraldas', (('Esmeraldas', 'Esmeraldas'), ('Eloy Alfaro', 'Eloy Alfaro'), ('Muisne', 'Muisne'), ('Quinindé', 'Quinindé'), ('San Lorenzo', 'San Lorenzo'), ('Atacames', 'Atacames'), ('Rioverde', 'Rioverde'))), ('Galápagos', (('San Cristóbal', 'San Cristóbal'), ('Isabela', 'Isabela'), ('Santa Cruz', 'Santa Cruz'))), ('Guayas', (('Guayaquil', 'Guayaquil'), ('Alfredo Baquerizo Moreno', 'Alfredo Baquerizo Moreno (Juján)'), ('Balao', 'Balao'), ('Balzar', 'Balzar'), ('Colimes', 'Colimes'), ('Coronel Marcelino Maridueña', 'Coronel Marcelino Maridueña'), ('Daule', 'Daule'), ('Durán', 'Durán'), ('El Empalme', 'El Empalme'), ('El Triunfo', 'El Triunfo'), ('Milagro', 'Milagro'), ('Naranjal', 'Naranjal'), ('Naranjito', 'Naranjito'), ('Palestina', 'Palestina'), ('Pedro Carbo', 'Pedro Carbo'), ('Samborondón', 'Samborondón'), ('Santa Lucía', 'Santa Lucía'), ('Simón Bolívar', 'Simón Bolívar'), ('Yaguachi', 'Yaguachi'), ('General Antonio Elizalde (Bucay)', 'General Antonio Elizalde (Bucay)'), ('Isidro Ayora', 'Isidro Ayora'), ('Lomas de Sargentillo', 'Lomas de Sargentillo'), ('Nobol', 'Nobol'), ('Santa Elena', 'Santa Elena'), ('La Libertad', 'La Libertad'), ('Salinas', 'Salinas'))), ('Imbabura', (('Ibarra', 'Ibarra'), ('Antonio Ante', 'Antonio Ante (Andrade Marin)'), ('Cotacachi', 'Cotacachi'), ('Otavalo', 'Otavalo'), ('Pimampiro', 'Pimampiro'), ('San Miguel de Urcuquí', 'San Miguel de Urcuquí'))), ('Loja', (('Loja', 'Loja'), ('Calvas', 'Calvas'), ('Catamayo', 'Catamayo'), ('Celica', 'Celica'), ('Chaguarpamba', 'Chaguarpamba'), ('Espíndola', 'Espíndola'), ('Gonzanamá', 'Gonzanamá'), ('Macará', 'Macará'), ('Paltas', 'Paltas'), ('Puyango', 'Puyango'), ('Saraguro', 'Saraguro'), ('Sozoranga', 'Sozoranga'), ('Zapotillo', 'Zapotillo'), ('Pindal', 'Pindal'), ('Quilanga', 'Quilanga'), ('Olmedo', 'Olmedo'))), ('Los Ríos', (('Babahoyo', 'Babahoyo'), ('Baba', 'Baba'), ('Montalvo', 'Montalvo'), ('Buena Fe', 'Buena Fe'), ('Mocache', 'Mocache'), ('Urdaneta', 'Urdaneta'), ('Ventanas', 'Ventanas'), ('Quevedo', 'Quevedo'), ('Quinsaloma', 'Quinsaloma'), ('Valencia', 'Valencia'), ('Vinces', 'Vinces'), ('Palenque', 'Palenque'))), ('Manabí', (('Portoviejo', 'Portoviejo'), ('Bolívar', 'Bolívar'), ('Chone', 'Chone'), ('El Carmen', 'El Carmen'), ('Flavio Alfaro', 'Flavio Alfaro'), ('Jipijapa', 'Jipijapa'), ('Junín', 'Junín'), ('Manta', 'Manta'), ('Montecristi', 'Montecristi'), ('Paján', 'Paján'), ('Pichincha', 'Pichincha'), ('Rocafuerte', 'Rocafuerte'), ('Santa Ana', 'Santa Ana'), ('Sucre', 'Sucre'), ('Tosagua', 'Tosagua'), ('24 de Mayo', '24 de Mayo'), ('Pedernales', 'Pedernales'), ('Olmedo', 'Olmedo'), ('Puerto López', 'Puerto López'), ('Jama', 'Jama'), ('San Vicente', 'San Vicente'))), ('Morona Santiago', (('Macas', 'Macas'), ('Gualaquiza', 'Gualaquiza'), ('Huamboya', 'Huamboya'), ('Limón Indanza', 'Limón Indanza'), ('Logroño', 'Logroño'), ('Morona', 'Morona'), ('Pablo Sexto', 'Pablo Sexto'), ('Palora', 'Palora'), ('San Juan Bosco', 'San Juan Bosco'), ('Santiago de Méndez', 'Santiago de Méndez'), ('Sucúa', 'Sucúa'), ('Taisha', 'Taisha'), ('Tiwintza', 'Tiwintza'))), ('Napo', (('Tena', 'Tena'), ('Archidona', 'Archidona'), ('El Chaco', 'El Chaco'), ('Quijos', 'Quijos'), ('Carlos Julio Arosemena Tola', 'Carlos Julio Arosemena Tola'))), ('Orellana', (('Orellana', 'Orellana'), ('Aguarico', 'Aguarico'), ('La Joya de los Sachas', 'La Joya de los Sachas'), ('Loreto', 'Loreto'))), ('Pastaza', (('Puyo', 'Puyo'), ('Arajuno', 'Arajuno'), ('Mera', 'Mera'), ('Santa Clara', 'Santa Clara'))), ('Pichincha', (('Quito', 'Quito'), ('Cayambe', 'Cayambe'), ('Mejía', 'Mejía'), ('Pedro Moncayo', 'Pedro Moncayo'), ('Rumiñahui', 'Rumiñahui'), ('San Miguel de los Bancos', 'San Miguel de los Bancos'), ('Pedro Vicente Maldonado', 'Pedro Vicente Maldonado'), ('Puerto Quito', 'Puerto Quito'))), ('Santa Elena', (('Santa Elena', 'Santa Elena'), ('La Libertad', 'La Libertad'), ('Salinas', 'Salinas'))), ('Santo Domingo de los Tsáchilas', (('Santo Domingo', 'Santo Domingo'), ('La Concordia', 'La Concordia'))), ('Sucumbíos', (('Nueva Loja', 'Nueva Loja'), ('Cascales', 'Cascales'), ('Cuyabeno', 'Cuyabeno'), ('Gonzalo Pizarro', 'Gonzalo Pizarro'), ('Putumayo', 'Putumayo'), ('Shushufindi', 'Shushufindi'), ('Sucumbíos', 'Sucumbíos'), ('Lago Agrio', 'Lago Agrio'))), ('Tungurahua', (('Ambato', 'Ambato'), ('Baños de Agua Santa', 'Baños de Agua Santa'), ('Cevallos', 'Cevallos'), ('Mocha', 'Mocha'), ('Patate', 'Patate'), ('Quero', 'Quero'), ('San Pedro de Pelileo', 'San Pedro de Pelileo'), ('Pelileo', 'Pelileo'), ('Pillaro', 'Pillaro'), ('Tisaleo', 'Tisaleo'))), ('Zamora Chinchipe', (('Zamora', 'Zamora'), ('Chinchipe', 'Chinchipe'), ('Centinela del Cóndor', 'Centinela del Cóndor'), ('Nangaritza', 'Nangaritza'), ('Palanda', 'Palanda'), ('Paquisha', 'Paquisha'), ('Yacuambi', 'Yacuambi'), ('Yantzaza', 'Yantzaza'), ('El Pangui', 'El Pangui')))], help_text='Si su pais de residencia es Ecuador, Elija una provincia. Caso contrario dejelo en blanco', max_length=255, null=True, verbose_name='Provincia y Cantones')),
                ('parroquia_quito', models.CharField(blank=True, choices=[('Conocoto', 'Conocoto'), ('Cumbayá', 'Cumbayá'), ('Chillogallo', 'Chillogallo'), ('Chilibulo', 'Chilibulo'), ('Chillos', 'Ch  illos'), ('Guamaní', 'Guamaní'), ('Calderón', 'Calderón'), ('Carapungo', 'Carapungo'), ('Pomasqui', 'Pomasqui'), ('Nayón', 'Nayón'), ('Tumbaco', 'Tumbaco'), ('Tababela', 'Tababela'), ('Quito', 'Quito')], help_text='Si su provincia de residencia es Pichincha, Elija una parroquia. Caso contrario dejelo en blanco', max_length=255, null=True, verbose_name='Parroquia de Quito')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('georeferenciacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Georreferenciación')),
                ('perfil_redes_sociales', models.URLField(blank=True, help_text='Pegue aquí la dirección Url de superfil de usuario en redes sociales.', null=True, verbose_name='Perfil de Redes Sociales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario')),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Contacto de Usuarios',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_artistica', models.CharField(choices=[('ARTES ESCÉNICAS', 'Artes Escénicas'), ('ARTES VISUALES O PLÁSTICAS', 'Artes Visuales o Plásticas'), ('ARTES MUSICALES', 'Artes Musicales'), ('ARTES AUDIOVISUALES', 'Artes Audiovisuales'), ('ARTES LITERARIAS', 'Artes Literarias'), ('ARTESANÍAS', 'Artesanías'), ('FORMACIÓN ARTÍSTICA', 'Formación Artística'), ('MEMORIA SOCIAL Y PATRIMONIO INTANGIBLE', 'Memoria Social y Patrimonio Intangible'), ('OTROS', 'Otros')], max_length=100, verbose_name='Disciplina/s Artística/s en la que enmarca sus actividades')),
                ('experiencia_ambito_cultural', models.TextField(blank=True, null=True, verbose_name='Experiencia en el ámbito cultural')),
                ('portafolio', models.URLField(blank=True, null=True, verbose_name='Portafolio')),
                ('registro_ruac', models.BooleanField(default=False, verbose_name='¿Es parte del Registro Único de Artistas y Gestores Culturales - RUAC?')),
                ('pertenece_agremiacion_colectivo', models.BooleanField(default=False, verbose_name='¿Pertenece a alguna Agremiación / Colectivo?')),
                ('nombre_agremiacion', models.CharField(blank=True, help_text='Si pertence a una agremiación artistica, escriba el nombre de la misma. Caso contrario, deje el campo en blanco. ', max_length=255, null=True, verbose_name='Nombre de la Agremiación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario')),
            ],
        ),
    ]
