# Generated by Django 4.2.13 on 2024-06-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='ruc',
            field=models.CharField(blank=True, help_text='SEscriba su R.U.C o C.I', max_length=13, null=True, verbose_name='RUC / C.I'),
        ),
    ]
