# Generated by Django 4.0.10 on 2024-08-02 01:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('banner_title4', wagtail.fields.RichTextField(blank=True, verbose_name='Título de galería-1')),
                ('TS_info1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtítulo info')),
                ('info1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Info')),
                ('banner_title5', wagtail.fields.RichTextField(blank=True, verbose_name='Título de galería-2')),
                ('TS_info2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtítulo-2 info')),
                ('info2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Info-2')),
                ('banner_title6', wagtail.fields.RichTextField(blank=True, verbose_name='Título de galería-3')),
                ('TS_info3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtítulo-3 info')),
                ('info3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Info-3')),
                ('banner_title7', wagtail.fields.RichTextField(blank=True, verbose_name='Título de galería-4')),
                ('TS_info4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtítulo-4 info')),
                ('info4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Info-4')),
                ('banner_title8', wagtail.fields.RichTextField(blank=True, verbose_name='Título de galería-5')),
                ('TS_info5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtítulo-5 info')),
                ('info5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Info-5')),
                ('banner_title9', wagtail.fields.RichTextField(blank=True, verbose_name='Título de galería-6')),
                ('TS_info6', models.CharField(blank=True, max_length=150, null=True, verbose_name='Subtítulo-6 info')),
                ('info6', models.CharField(blank=True, max_length=150, null=True, verbose_name='Info-6')),
                ('banner_title10', wagtail.fields.RichTextField(blank=True, verbose_name='Mejoramos')),
                ('info7', models.CharField(blank=True, max_length=150, null=True, verbose_name='IT Business Analytics')),
                ('info8', models.CharField(blank=True, max_length=150, null=True, verbose_name='IT Business Cloud DevOps')),
                ('info9', models.CharField(blank=True, max_length=150, null=True, verbose_name='IT Business Media')),
                ('product_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Producto-1')),
                ('product_description_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Producto-1')),
                ('product_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Producto-2')),
                ('product_description_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Producto-2')),
                ('product_3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Producto-3')),
                ('product_description_3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Producto-3')),
                ('product_4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Producto-4')),
                ('product_description_4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Producto-4')),
                ('product_5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Producto-5')),
                ('product_description_5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Producto-5')),
                ('product_6', models.CharField(blank=True, max_length=150, null=True, verbose_name='Producto-6')),
                ('product_description_6', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Producto-6')),
                ('numero_coffe', models.IntegerField(blank=True, null=True)),
                ('numero_experiencia', models.IntegerField(blank=True, null=True)),
                ('numero_horas', models.IntegerField(blank=True, null=True)),
                ('numero_wins', models.IntegerField(blank=True, null=True)),
                ('team_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Equipo-1')),
                ('team_descrp_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Equipo-1')),
                ('team_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Equipo-2')),
                ('team_descrp_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Equipo-2')),
                ('team_3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Equipo-3')),
                ('team_descrp_3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Equipo-3')),
                ('team_4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Equipo-4')),
                ('team_descrp_4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción Equipo-4')),
                ('banner_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título de llamada a la acción')),
                ('slogan', models.CharField(blank=True, max_length=150, null=True, verbose_name='Slogan')),
                ('slogan_descriptcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción del Slogan')),
                ('custom_title', models.CharField(blank=True, help_text='Reescribe el Título de la publicación', max_length=100, null=True)),
                ('consulta', wagtail.fields.RichTextField(blank=True, verbose_name='Mensaje para consulta')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('pinterest', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GaleriaHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1')),
                ('image_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 2')),
                ('image_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 3')),
                ('image_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 4')),
                ('image_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 5')),
                ('image_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 6')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo SmartQuail')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria', to='webapp.home')),
                ('profile_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto de perfil')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultasHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='webapp.home')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
