# Generated by Django 4.2.16 on 2024-12-03 01:35

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbusinessmedia_info',
            name='banner_title16',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo-3'),
        ),
        migrations.AddField(
            model_name='smartbusinessmedia_info',
            name='banner_title17',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Titulo de parrafo-3'),
        ),
        migrations.AddField(
            model_name='smartbusinessmedia_info',
            name='info_title16',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Descripcion de producto'),
        ),
        migrations.AddField(
            model_name='smartbusinessmedia_info',
            name='info_title17',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Descripcion de producto'),
        ),
    ]
