# Generated by Django 4.0.10 on 2024-08-04 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webapp', '0002_alter_consultashome_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriahome',
            name='image_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 10'),
        ),
        migrations.AddField(
            model_name='galeriahome',
            name='image_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 11'),
        ),
        migrations.AddField(
            model_name='galeriahome',
            name='image_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 7'),
        ),
        migrations.AddField(
            model_name='galeriahome',
            name='image_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 8'),
        ),
        migrations.AddField(
            model_name='galeriahome',
            name='image_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 9'),
        ),
    ]
