# Generated by Django 4.0.10 on 2024-08-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('webapp', '0003_galeriahome_image_10_galeriahome_image_11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriahome',
            name='image_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 11'),
        ),
        migrations.AddField(
            model_name='galeriahome',
            name='image_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 11'),
        ),
        migrations.AddField(
            model_name='galeriahome',
            name='image_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 11'),
        ),
        migrations.AddField(
            model_name='galeriahome',
            name='image_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 11'),
        ),
    ]
