# Generated by Django 4.0.10 on 2024-08-11 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('webapp', '0007_info_galeriadeimagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLinksSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacus', models.URLField(blank=True, null=True)),
                ('start_project_SBM', models.URLField(blank=True, null=True)),
                ('start_project_SBL', models.URLField(blank=True, null=True)),
                ('start_project_SBA', models.URLField(blank=True, null=True)),
                ('start_project_SBT', models.URLField(blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
