# Generated by Django 4.2.16 on 2024-12-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmorders', '0002_banktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='invoice',
            field=models.FileField(blank=True, upload_to='products/smartbusinessmedia/CUSTOMERSTRANSFERS/%Y/%m/%d'),
        ),
    ]
