# Generated by Django 4.2.16 on 2024-12-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmorders', '0003_banktransfer_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransfer',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='banktransfer',
            name='product',
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='transfer_date',
            field=models.DateField(auto_now=True),
        ),
    ]
