# Generated by Django 4.2.16 on 2024-12-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmorders', '0006_alter_banktransfer_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransfer',
            name='invoice',
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='accept_terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Acepta los términos y condiciones del contrato'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado de pago'),
        ),
    ]
