# Generated by Django 4.2.16 on 2024-12-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmorders', '0007_remove_banktransfer_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='bank',
            field=models.CharField(choices=[('banco_pichincha', 'Banco de Pichincha'), ('produbanco', 'Banco Produbanco'), ('banco_internacional', 'Banco Internacional'), ('banco_guayaquil', 'Banco de Guayaquil'), ('banco_bolivariano', 'Banco Bolivariano'), ('banco_del_achira', 'Banco del Austro'), ('banco_de_los_andes', 'Banco de los Andes'), ('banco_comercial', 'Banco Comercial'), ('banco_territorial', 'Banco Territorial'), ('banco_nacional_de_fomento', 'Banco Nacional de Fomento'), ('banco_pacifico', 'Banco Pacífico'), ('banco_procredit', 'Banco ProCredit'), ('banco_machala', 'Banco de Machala'), ('banco_de_la_produccion', 'Banco de la Producción'), ('banco_davivienda', 'Banco Davivienda Ecuador'), ('banco_de_guayaquil_vision', 'Banco de Guayaquil Visión'), ('banco_union', 'Banco Unión'), ('banco_solidario', 'Banco Solidario'), ('banco_mercantil', 'Banco Mercantil'), ('banco_rural', 'Banco Rural'), ('banco_suramericano', 'Banco Suramericano')], max_length=500),
        ),
    ]
