# Generated by Django 4.2.16 on 2024-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmorders', '0012_order_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accept_terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Acepta los términos y condiciones del contrato'),
        ),
    ]
