# Generated by Django 4.2.16 on 2024-12-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmorders', '0013_order_accept_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Tarjeta de Crédito'), ('bank_transfer', 'Transferencia Bancaria'), ('paypal', 'PayPal'), ('amazon_pay', 'Amazon Pay'), ('apple_pay', 'Apple Pay')], null=True),
        ),
    ]
