# Generated by Django 4.2.16 on 2024-12-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbmorders', '0014_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Tarjeta de Crédito'), ('bank_transfer', 'Transferencia Bancaria'), ('paypal', 'PayPal'), ('amazon_pay', 'Amazon Pay')], null=True),
        ),
    ]
