version: "3.3"

services:
  qnd10app:
    image: smartquail/qnd10app:latest
    restart: unless-stopped
    environment:
      - PORT=9000
    env_file:
      - .env
    depends_on:
      - smartquaildb
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/staticfiles
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/media
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/static

  smartquaildb:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: always
    command: "postgres -p 5432"  # Agregué comillas al valor del comando
    expose:
      - 5432
    volumes:
      - smartquaildb_data-qnode10:/var/lib/postgresql/data/

  nginx:
    image: smartquail/qnd10_nginx:prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=80
    depends_on:
      - qnd10app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/staticfiles
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/media
      - static-data-qnd10:/qnd10app/qnd10app/qnd10app/static
      - certbot-web_2:/vol/www
      - proxy-dhparams_2:/vol/proxy
      - letsencrypt_certs:/etc/letsencrypt/

  jmeter-master:
    image: smartquail/qnd10_jmeter:prod
    restart: unless-stopped
    container_name: jmeter-master
    env_file:
      - .env
    command: >
      -n -t /jmeter/scripts/qnd10_test_plan.jmx \
      -l /jmeter/results/qnd10_results.jtl \
      -e -o /jmeter/qnd10_web_report
    ports:
      - "60000:60000"  # Puerto para la comunicación con los slaves
      - "1099:1099"    # Puerto RMI
   # volumes:
   #   - jmeter_scripts:/jmeter/scripts  # Directorio que contiene los scripts de JMeter
   #   - jmeter_results:/jmeter/results  # Directorio donde se guardarán los resultados

  jmeter-slave:
    image: smartquail/qnd10_jmeter:prod
    container_name: jmeter-slave
    env_file:
      - .env
    depends_on:
      - jmeter-master
    command: >
      -n -t /jmeter/scripts/qnd10_test_plan.jmx \
      -l /jmeter/results/qnd10_results.jtl \
      -e -o /jmeter/qnd10_web_report \
      -Jserver.rmi.ssl.disable=true \
      -Djava.rmi.server.hostname=jmeter-master \
      -Dclient.rmi.localport=60000 \
      -Dclient.rmi.ssl.disable=true \
      -Dserver.rmi.localport=60000 \
      -Dserver.rmi.port=60000 \
      -Dserver.rmi.ssl.disable=true \
      -Dserver.rmi.service.port=60000 \
      -Dserver.rmi.registry.port=1099
    volumes:
      - jmeter_scripts:/jmeter/scripts  # Directorio que contiene los scripts de JMeter
      - jmeter_results:/jmeter/results  # Directorio donde se guardarán los resultados

  jmeter_GUI:
    image: guitarrapc/jmeter-gui:latest
    tty: true
    volumes:
      - ./scenario/:/root/jmeter/
    ports:
      - 5900:5900
      - 3390:3389

volumes:
  jmeter_scripts:
  jmeter_results:
  certbot-web_2:
  proxy-dhparams_2:
  letsencrypt_certs:
  static-data-qnd10:
  smartquaildb_data-qnode10:
