# Generated by Django 4.2.13 on 2024-06-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_literaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='portada_2',
            field=models.ImageField(blank=True, upload_to='portada/%Y/%m/%d/', verbose_name='Foto de portada 2 de convocatoria'),
        ),
        migrations.AddField(
            model_name='course',
            name='portada_3',
            field=models.ImageField(blank=True, upload_to='portada/%Y/%m/%d/', verbose_name='Foto de portada 3 de convocatoria'),
        ),
        migrations.AlterField(
            model_name='course',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portada/%Y/%m/%d/', verbose_name='Foto de portada 1 de convocatoria'),
        ),
    ]
