# Generated by Django 4.2.18 on 2025-02-08 00:55

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_emailcampaignsnippet_remove_emailcampaign_expire_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCampaignSnippet',
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='message',
            field=wagtail.fields.RichTextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='recipient',
            field=models.EmailField(max_length=254, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='send_date',
            field=models.DateTimeField(verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Enviado'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Asunto'),
        ),
    ]
